### ISSUE TITLE
Elasticsearch Container always fails when using M2

### ISSUE THREAD

**Issue by jaydee18** [ddev/ddev-elasticsearch#12]
Hello,

I'm trying to add Elastic Search to my project running on DDEV using Colima on an M2 Mac. The container never seems to spin up unless I run my Terminal in Rosetta mode.

**Comment by rfay** [comment]
If you take a look at https://hub.docker.com/_/elasticsearch/tags?page=1&name=7.17.6 you see that both amd64 and arm64 images are available, so you shouldn't need rosetta. 

How are you installing this? Are you changing it at all?

I absolutely don't recommend running with rosetta, and the way to use colima with rosetta is not to run your terminal with rosetta.

Are you using the arm64 version of colima? What does `file $(which colima)` say?

**Comment by rfay** [comment]
I just did a `ddev get ddev/ddev-elasticsearth && ddev restart` using Colima 0.5.5 on Apple Silicon without any trouble. 

I imagine you may have homebrew set up wrong? If you have homebrew installed in /usr/local/bin, that's the amd64 version of homebrew, and you'll have to uninstall and install properly on your Apple Silicon machine. Homebrew and all of its installations are in /opt/homebrew on Apple Silicon, not in /usr/local/bin.

**Comment by rfay** [comment]
Closing, no response.
